2025-10-07 02:09:25,664 - util.py[DEBUG]: Cloud-init v. 22.2.2 running 'init' at Tue, 07 Oct 2025 02:09:25 +0000. Up 7.26 seconds.
2025-10-07 02:09:25,664 - main.py[DEBUG]: No kernel command line url found.
2025-10-07 02:09:25,664 - main.py[DEBUG]: Closing stdin.
2025-10-07 02:09:25,667 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud (recursive=False)
2025-10-07 02:09:25,667 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud (recursive=True)
2025-10-07 02:09:25,671 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts (recursive=False)
2025-10-07 02:09:25,680 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts (recursive=True)
2025-10-07 02:09:25,683 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts/per-instance (recursive=False)
2025-10-07 02:09:25,683 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts (recursive=True)
2025-10-07 02:09:25,686 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts/per-once (recursive=False)
2025-10-07 02:09:25,688 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts (recursive=True)
2025-10-07 02:09:25,692 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts/per-boot (recursive=False)
2025-10-07 02:09:25,700 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts (recursive=True)
2025-10-07 02:09:25,705 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts/vendor (recursive=False)
2025-10-07 02:09:25,706 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud (recursive=True)
2025-10-07 02:09:25,714 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/seed (recursive=False)
2025-10-07 02:09:25,715 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud (recursive=True)
2025-10-07 02:09:25,724 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances (recursive=False)
2025-10-07 02:09:25,725 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud (recursive=True)
2025-10-07 02:09:25,734 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/handlers (recursive=False)
2025-10-07 02:09:25,734 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud (recursive=True)
2025-10-07 02:09:25,744 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/sem (recursive=False)
2025-10-07 02:09:25,745 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data (recursive=False)
2025-10-07 02:09:25,745 - util.py[DEBUG]: Restoring selinux mode for /run/cloud-init (recursive=True)
2025-10-07 02:09:25,746 - util.py[DEBUG]: Restoring selinux mode for /run/cloud-init/sem (recursive=False)
2025-10-07 02:09:25,746 - util.py[DEBUG]: Writing to /var/log/cloud-init.log - ab: [640] 0 bytes
2025-10-07 02:09:25,748 - util.py[DEBUG]: Restoring selinux mode for /var/log/cloud-init.log (recursive=False)
2025-10-07 02:09:25,748 - util.py[DEBUG]: Restoring selinux mode for /var/log/cloud-init.log (recursive=False)
2025-10-07 02:09:25,749 - util.py[DEBUG]: Changing the ownership of /var/log/cloud-init.log to 0:4
2025-10-07 02:09:25,749 - util.py[DEBUG]: Writing to /var/lib/cloud/data/python-version - wb: [644] 3 bytes
2025-10-07 02:09:25,749 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/python-version (recursive=False)
2025-10-07 02:09:25,750 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/python-version (recursive=False)
2025-10-07 02:09:25,750 - subp.py[DEBUG]: Running command ['ip', '--json', 'addr'] with allowed return codes [0] (shell=False, capture=True)
2025-10-07 02:09:25,755 - subp.py[DEBUG]: Running command ['ip', '-o', 'route', 'list'] with allowed return codes [0] (shell=False, capture=True)
2025-10-07 02:09:25,759 - subp.py[DEBUG]: Running command ['ip', '--oneline', '-6', 'route', 'list', 'table', 'all'] with allowed return codes [0, 1] (shell=False, capture=True)
2025-10-07 02:09:25,770 - handlers.py[DEBUG]: start: init-network/check-cache: attempting to read from cache [trust]
2025-10-07 02:09:25,775 - util.py[DEBUG]: Reading from /var/lib/cloud/instance/obj.pkl (quiet=False)
2025-10-07 02:09:25,777 - stages.py[DEBUG]: no cache found
2025-10-07 02:09:25,779 - handlers.py[DEBUG]: finish: init-network/check-cache: SUCCESS: no cache found
2025-10-07 02:09:25,779 - util.py[DEBUG]: Attempting to remove /var/lib/cloud/instance
2025-10-07 02:09:25,796 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.amazon.Distro'>
2025-10-07 02:09:25,796 - __init__.py[DEBUG]: Looking for data source in: ['Ec2', 'None'], via packages ['', 'cloudinit.sources'] that matches dependencies ['FILESYSTEM', 'NETWORK']
2025-10-07 02:09:25,801 - __init__.py[DEBUG]: Searching for network data source in: ['DataSourceEc2', 'DataSourceNone']
2025-10-07 02:09:25,802 - handlers.py[DEBUG]: start: init-network/search-Ec2: searching for network data from DataSourceEc2
2025-10-07 02:09:25,802 - __init__.py[DEBUG]: Seeing if we can get any data from <class 'cloudinit.sources.DataSourceEc2.DataSourceEc2'>
2025-10-07 02:09:25,802 - __init__.py[DEBUG]: Update datasource metadata and network config due to events: boot-new-instance
2025-10-07 02:09:25,802 - util.py[DEBUG]: Reading from /sys/hypervisor/uuid (quiet=False)
2025-10-07 02:09:25,802 - dmi.py[DEBUG]: querying dmi data /sys/class/dmi/id/product_uuid
2025-10-07 02:09:25,802 - dmi.py[DEBUG]: querying dmi data /sys/class/dmi/id/product_serial
2025-10-07 02:09:25,802 - dmi.py[DEBUG]: querying dmi data /sys/class/dmi/id/chassis_asset_tag
2025-10-07 02:09:25,802 - dmi.py[DEBUG]: querying dmi data /sys/class/dmi/id/sys_vendor
2025-10-07 02:09:25,803 - DataSourceEc2.py[DEBUG]: strict_mode: warn, cloud_name=aws cloud_platform=ec2
2025-10-07 02:09:25,803 - util.py[DEBUG]: Skipping DNS checks of IP address 169.254.169.254
2025-10-07 02:09:25,803 - util.py[DEBUG]: Resolving URL: http://169.254.169.254:80 took 0.000 seconds
2025-10-07 02:09:25,803 - util.py[DEBUG]: Skipping DNS checks of IP address fd00:ec2::254
2025-10-07 02:09:25,803 - util.py[DEBUG]: Resolving URL: http://[fd00:ec2::254]:80 took 0.000 seconds
2025-10-07 02:09:25,803 - DataSourceEc2.py[DEBUG]: Fetching Ec2 IMDSv2 API Token
2025-10-07 02:09:25,810 - url_helper.py[DEBUG]: [0/1] open 'http://169.254.169.254:80/latest/api/token' with {'url': 'http://169.254.169.254:80/latest/api/token', 'allow_redirects': True, 'method': 'PUT', 'timeout': 50.0, 'headers': {'User-Agent': 'Cloud-Init/22.2.2', 'X-aws-ec2-metadata-token-ttl-seconds': 'REDACTED'}} configuration
2025-10-07 02:09:25,817 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/latest/api/token (200, 56b) after 1 attempts
2025-10-07 02:09:25,817 - DataSourceEc2.py[DEBUG]: Using metadata source: 'http://169.254.169.254:80'
2025-10-07 02:09:25,817 - url_helper.py[DEBUG]: [0/1] open 'http://169.254.169.254:80/2021-03-23/meta-data/instance-id' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/instance-id', 'allow_redirects': True, 'method': 'GET', 'headers': {'User-Agent': 'Cloud-Init/22.2.2', 'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-10-07 02:09:25,820 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/instance-id (200, 19b) after 1 attempts
2025-10-07 02:09:25,820 - DataSourceEc2.py[DEBUG]: Found preferred metadata version 2021-03-23
2025-10-07 02:09:25,820 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/user-data' with {'url': 'http://169.254.169.254:80/2021-03-23/user-data', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-10-07 02:09:25,822 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/user-data (200, 2480b) after 1 attempts
2025-10-07 02:09:25,823 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-10-07 02:09:25,825 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/ (200, 305b) after 1 attempts
2025-10-07 02:09:25,825 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/block-device-mapping/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/block-device-mapping/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-10-07 02:09:25,827 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/block-device-mapping/ (200, 8b) after 1 attempts
2025-10-07 02:09:25,827 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/block-device-mapping/ami' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/block-device-mapping/ami', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-10-07 02:09:25,830 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/block-device-mapping/ami (200, 4b) after 1 attempts
2025-10-07 02:09:25,831 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/block-device-mapping/root' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/block-device-mapping/root', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-10-07 02:09:25,833 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/block-device-mapping/root (200, 9b) after 1 attempts
2025-10-07 02:09:25,833 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/events/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/events/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-10-07 02:09:25,835 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/events/ (200, 12b) after 1 attempts
2025-10-07 02:09:25,835 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/events/maintenance/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/events/maintenance/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-10-07 02:09:25,837 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/events/maintenance/ (200, 17b) after 1 attempts
2025-10-07 02:09:25,837 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/events/maintenance/history' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/events/maintenance/history', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-10-07 02:09:25,839 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/events/maintenance/history (200, 2b) after 1 attempts
2025-10-07 02:09:25,839 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/events/maintenance/scheduled' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/events/maintenance/scheduled', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-10-07 02:09:25,841 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/events/maintenance/scheduled (200, 2b) after 1 attempts
2025-10-07 02:09:25,842 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/iam/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/iam/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-10-07 02:09:25,844 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/iam/ (200, 26b) after 1 attempts
2025-10-07 02:09:25,844 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/iam/info' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/iam/info', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-10-07 02:09:25,846 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/iam/info (200, 216b) after 1 attempts
2025-10-07 02:09:25,846 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/identity-credentials/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/identity-credentials/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-10-07 02:09:25,848 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/identity-credentials/ (200, 4b) after 1 attempts
2025-10-07 02:09:25,848 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/identity-credentials/ec2/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/identity-credentials/ec2/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-10-07 02:09:25,850 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/identity-credentials/ec2/ (200, 26b) after 1 attempts
2025-10-07 02:09:25,850 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/identity-credentials/ec2/info' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/identity-credentials/ec2/info', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-10-07 02:09:25,852 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/identity-credentials/ec2/info (200, 98b) after 1 attempts
2025-10-07 02:09:25,852 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/metrics/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/metrics/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-10-07 02:09:25,854 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/metrics/ (200, 7b) after 1 attempts
2025-10-07 02:09:25,854 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/metrics/vhostmd' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/metrics/vhostmd', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-10-07 02:09:25,857 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/metrics/vhostmd (200, 38b) after 1 attempts
2025-10-07 02:09:25,857 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-10-07 02:09:25,859 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/ (200, 11b) after 1 attempts
2025-10-07 02:09:25,859 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-10-07 02:09:25,861 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/ (200, 5b) after 1 attempts
2025-10-07 02:09:25,861 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-10-07 02:09:25,863 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/ (200, 18b) after 1 attempts
2025-10-07 02:09:25,863 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:ce:33:05:ae:d9/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:ce:33:05:ae:d9/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-10-07 02:09:25,867 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:ce:33:05:ae:d9/ (200, 230b) after 1 attempts
2025-10-07 02:09:25,867 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:ce:33:05:ae:d9/ipv4-associations/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:ce:33:05:ae:d9/ipv4-associations/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-10-07 02:09:25,869 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:ce:33:05:ae:d9/ipv4-associations/ (200, 12b) after 1 attempts
2025-10-07 02:09:25,870 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:ce:33:05:ae:d9/ipv4-associations/3.149.120.21' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:ce:33:05:ae:d9/ipv4-associations/3.149.120.21', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-10-07 02:09:25,872 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:ce:33:05:ae:d9/ipv4-associations/3.149.120.21 (200, 12b) after 1 attempts
2025-10-07 02:09:25,872 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:ce:33:05:ae:d9/device-number' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:ce:33:05:ae:d9/device-number', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-10-07 02:09:25,874 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:ce:33:05:ae:d9/device-number (200, 1b) after 1 attempts
2025-10-07 02:09:25,874 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:ce:33:05:ae:d9/interface-id' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:ce:33:05:ae:d9/interface-id', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-10-07 02:09:25,876 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:ce:33:05:ae:d9/interface-id (200, 21b) after 1 attempts
2025-10-07 02:09:25,876 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:ce:33:05:ae:d9/local-hostname' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:ce:33:05:ae:d9/local-hostname', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-10-07 02:09:25,878 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:ce:33:05:ae:d9/local-hostname (200, 42b) after 1 attempts
2025-10-07 02:09:25,878 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:ce:33:05:ae:d9/local-ipv4s' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:ce:33:05:ae:d9/local-ipv4s', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-10-07 02:09:25,881 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:ce:33:05:ae:d9/local-ipv4s (200, 12b) after 1 attempts
2025-10-07 02:09:25,881 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:ce:33:05:ae:d9/mac' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:ce:33:05:ae:d9/mac', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-10-07 02:09:25,883 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:ce:33:05:ae:d9/mac (200, 17b) after 1 attempts
2025-10-07 02:09:25,883 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:ce:33:05:ae:d9/owner-id' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:ce:33:05:ae:d9/owner-id', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-10-07 02:09:25,885 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:ce:33:05:ae:d9/owner-id (200, 12b) after 1 attempts
2025-10-07 02:09:25,885 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:ce:33:05:ae:d9/public-hostname' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:ce:33:05:ae:d9/public-hostname', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-10-07 02:09:25,887 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:ce:33:05:ae:d9/public-hostname (200, 48b) after 1 attempts
2025-10-07 02:09:25,887 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:ce:33:05:ae:d9/public-ipv4s' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:ce:33:05:ae:d9/public-ipv4s', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-10-07 02:09:25,889 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:ce:33:05:ae:d9/public-ipv4s (200, 12b) after 1 attempts
2025-10-07 02:09:25,889 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:ce:33:05:ae:d9/security-group-ids' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:ce:33:05:ae:d9/security-group-ids', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-10-07 02:09:25,891 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:ce:33:05:ae:d9/security-group-ids (200, 20b) after 1 attempts
2025-10-07 02:09:25,891 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:ce:33:05:ae:d9/security-groups' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:ce:33:05:ae:d9/security-groups', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-10-07 02:09:25,893 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:ce:33:05:ae:d9/security-groups (200, 56b) after 1 attempts
2025-10-07 02:09:25,893 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:ce:33:05:ae:d9/subnet-id' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:ce:33:05:ae:d9/subnet-id', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-10-07 02:09:25,895 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:ce:33:05:ae:d9/subnet-id (200, 24b) after 1 attempts
2025-10-07 02:09:25,895 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:ce:33:05:ae:d9/subnet-ipv4-cidr-block' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:ce:33:05:ae:d9/subnet-ipv4-cidr-block', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-10-07 02:09:25,897 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:ce:33:05:ae:d9/subnet-ipv4-cidr-block (200, 13b) after 1 attempts
2025-10-07 02:09:25,897 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:ce:33:05:ae:d9/vpc-id' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:ce:33:05:ae:d9/vpc-id', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-10-07 02:09:25,899 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:ce:33:05:ae:d9/vpc-id (200, 21b) after 1 attempts
2025-10-07 02:09:25,899 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:ce:33:05:ae:d9/vpc-ipv4-cidr-block' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:ce:33:05:ae:d9/vpc-ipv4-cidr-block', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-10-07 02:09:25,901 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:ce:33:05:ae:d9/vpc-ipv4-cidr-block (200, 13b) after 1 attempts
2025-10-07 02:09:25,901 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:ce:33:05:ae:d9/vpc-ipv4-cidr-blocks' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:ce:33:05:ae:d9/vpc-ipv4-cidr-blocks', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-10-07 02:09:25,903 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:ce:33:05:ae:d9/vpc-ipv4-cidr-blocks (200, 13b) after 1 attempts
2025-10-07 02:09:25,903 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/placement/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/placement/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-10-07 02:09:25,905 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/placement/ (200, 45b) after 1 attempts
2025-10-07 02:09:25,905 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/placement/availability-zone' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/placement/availability-zone', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-10-07 02:09:25,907 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/placement/availability-zone (200, 10b) after 1 attempts
2025-10-07 02:09:25,907 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/placement/availability-zone-id' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/placement/availability-zone-id', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-10-07 02:09:25,909 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/placement/availability-zone-id (200, 8b) after 1 attempts
2025-10-07 02:09:25,909 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/placement/region' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/placement/region', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-10-07 02:09:25,911 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/placement/region (200, 9b) after 1 attempts
2025-10-07 02:09:25,912 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/services/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/services/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-10-07 02:09:25,914 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/services/ (200, 16b) after 1 attempts
2025-10-07 02:09:25,914 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/services/domain' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/services/domain', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-10-07 02:09:25,916 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/services/domain (200, 13b) after 1 attempts
2025-10-07 02:09:25,916 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/services/partition' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/services/partition', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-10-07 02:09:25,918 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/services/partition (200, 3b) after 1 attempts
2025-10-07 02:09:25,919 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/ami-id' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/ami-id', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-10-07 02:09:25,921 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/ami-id (200, 21b) after 1 attempts
2025-10-07 02:09:25,921 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/ami-launch-index' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/ami-launch-index', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-10-07 02:09:25,923 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/ami-launch-index (200, 1b) after 1 attempts
2025-10-07 02:09:25,924 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/ami-manifest-path' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/ami-manifest-path', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-10-07 02:09:25,926 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/ami-manifest-path (200, 9b) after 1 attempts
2025-10-07 02:09:25,926 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/hostname' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/hostname', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-10-07 02:09:25,929 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/hostname (200, 42b) after 1 attempts
2025-10-07 02:09:25,929 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/instance-action' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/instance-action', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-10-07 02:09:25,931 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/instance-action (200, 4b) after 1 attempts
2025-10-07 02:09:25,931 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/instance-id' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/instance-id', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-10-07 02:09:25,933 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/instance-id (200, 19b) after 1 attempts
2025-10-07 02:09:25,933 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/instance-life-cycle' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/instance-life-cycle', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-10-07 02:09:25,936 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/instance-life-cycle (200, 9b) after 1 attempts
2025-10-07 02:09:25,936 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/instance-type' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/instance-type', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-10-07 02:09:25,938 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/instance-type (200, 8b) after 1 attempts
2025-10-07 02:09:25,938 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/local-hostname' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/local-hostname', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-10-07 02:09:25,940 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/local-hostname (200, 42b) after 1 attempts
2025-10-07 02:09:25,941 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/local-ipv4' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/local-ipv4', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-10-07 02:09:25,942 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/local-ipv4 (200, 12b) after 1 attempts
2025-10-07 02:09:25,943 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/mac' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/mac', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-10-07 02:09:25,945 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/mac (200, 17b) after 1 attempts
2025-10-07 02:09:25,945 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/profile' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/profile', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-10-07 02:09:25,946 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/profile (200, 11b) after 1 attempts
2025-10-07 02:09:25,947 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/public-hostname' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/public-hostname', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-10-07 02:09:25,949 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/public-hostname (200, 48b) after 1 attempts
2025-10-07 02:09:25,949 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/public-ipv4' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/public-ipv4', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-10-07 02:09:25,951 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/public-ipv4 (200, 12b) after 1 attempts
2025-10-07 02:09:25,951 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/reservation-id' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/reservation-id', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-10-07 02:09:25,953 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/reservation-id (200, 19b) after 1 attempts
2025-10-07 02:09:25,953 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/security-groups' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/security-groups', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-10-07 02:09:25,955 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/security-groups (200, 56b) after 1 attempts
2025-10-07 02:09:25,955 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity' with {'url': 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-10-07 02:09:25,957 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/dynamic/instance-identity (200, 32b) after 1 attempts
2025-10-07 02:09:25,957 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/document' with {'url': 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/document', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-10-07 02:09:25,959 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/document (200, 476b) after 1 attempts
2025-10-07 02:09:25,959 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/pkcs7' with {'url': 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/pkcs7', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-10-07 02:09:25,961 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/pkcs7 (200, 1171b) after 1 attempts
2025-10-07 02:09:25,961 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/rsa2048' with {'url': 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/rsa2048', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-10-07 02:09:25,963 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/rsa2048 (200, 1491b) after 1 attempts
2025-10-07 02:09:25,963 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/signature' with {'url': 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/signature', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-10-07 02:09:25,965 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/signature (200, 174b) after 1 attempts
2025-10-07 02:09:25,965 - util.py[DEBUG]: Crawl of metadata service took 0.162 seconds
2025-10-07 02:09:25,967 - util.py[DEBUG]: Writing to /run/cloud-init/cloud-id-aws - wb: [644] 4 bytes
2025-10-07 02:09:25,968 - util.py[DEBUG]: Restoring selinux mode for /run/cloud-init/cloud-id-aws (recursive=False)
2025-10-07 02:09:25,969 - util.py[DEBUG]: Restoring selinux mode for /run/cloud-init/cloud-id-aws (recursive=False)
2025-10-07 02:09:25,969 - util.py[DEBUG]: Creating symbolic link from '/run/cloud-init/cloud-id' => '/run/cloud-init/cloud-id-aws'
2025-10-07 02:09:25,970 - atomic_helper.py[DEBUG]: Atomically writing to file /run/cloud-init/instance-data-sensitive.json (via temporary file /run/cloud-init/tmptr8qmh0a) - w: [600] 12020 bytes/chars
2025-10-07 02:09:25,970 - atomic_helper.py[DEBUG]: Atomically writing to file /run/cloud-init/instance-data.json (via temporary file /run/cloud-init/tmpxe4nzgmn) - w: [644] 7878 bytes/chars
2025-10-07 02:09:25,971 - handlers.py[DEBUG]: finish: init-network/search-Ec2: SUCCESS: found network data from DataSourceEc2
2025-10-07 02:09:25,971 - stages.py[INFO]: Loaded datasource DataSourceEc2 - DataSourceEc2
2025-10-07 02:09:25,971 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg (quiet=False)
2025-10-07 02:09:25,971 - util.py[DEBUG]: Read 2553 bytes from /etc/cloud/cloud.cfg
2025-10-07 02:09:25,971 - util.py[DEBUG]: Attempting to load yaml from string of length 2553 with allowed root types (<class 'dict'>,)
2025-10-07 02:09:25,978 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/40_selinux-reboot.cfg (quiet=False)
2025-10-07 02:09:25,978 - util.py[DEBUG]: Read 174 bytes from /etc/cloud/cloud.cfg.d/40_selinux-reboot.cfg
2025-10-07 02:09:25,978 - util.py[DEBUG]: Attempting to load yaml from string of length 174 with allowed root types (<class 'dict'>,)
2025-10-07 02:09:25,979 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/10_aws_dnfvars.cfg (quiet=False)
2025-10-07 02:09:25,979 - util.py[DEBUG]: Read 591 bytes from /etc/cloud/cloud.cfg.d/10_aws_dnfvars.cfg
2025-10-07 02:09:25,979 - util.py[DEBUG]: Attempting to load yaml from string of length 591 with allowed root types (<class 'dict'>,)
2025-10-07 02:09:25,981 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/05_logging.cfg (quiet=False)
2025-10-07 02:09:25,981 - util.py[DEBUG]: Read 2070 bytes from /etc/cloud/cloud.cfg.d/05_logging.cfg
2025-10-07 02:09:25,981 - util.py[DEBUG]: Attempting to load yaml from string of length 2070 with allowed root types (<class 'dict'>,)
2025-10-07 02:09:25,983 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/01_amazon-ec2.cfg (quiet=False)
2025-10-07 02:09:25,984 - util.py[DEBUG]: Read 237 bytes from /etc/cloud/cloud.cfg.d/01_amazon-ec2.cfg
2025-10-07 02:09:25,984 - util.py[DEBUG]: Attempting to load yaml from string of length 237 with allowed root types (<class 'dict'>,)
2025-10-07 02:09:25,985 - util.py[DEBUG]: Reading from /run/cloud-init/cloud.cfg (quiet=False)
2025-10-07 02:09:25,985 - util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<class 'dict'>,)
2025-10-07 02:09:25,985 - util.py[DEBUG]: loaded blob returned None, returning default.
2025-10-07 02:09:25,986 - util.py[DEBUG]: Attempting to remove /var/lib/cloud/instance
2025-10-07 02:09:25,986 - util.py[DEBUG]: Creating symbolic link from '/var/lib/cloud/instance' => '/var/lib/cloud/instances/i-03facd8bcdc8558f2'
2025-10-07 02:09:25,986 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-03facd8bcdc8558f2 (recursive=True)
2025-10-07 02:09:25,990 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-03facd8bcdc8558f2/handlers (recursive=False)
2025-10-07 02:09:25,990 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-03facd8bcdc8558f2 (recursive=True)
2025-10-07 02:09:25,994 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-03facd8bcdc8558f2/scripts (recursive=False)
2025-10-07 02:09:25,994 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-03facd8bcdc8558f2 (recursive=True)
2025-10-07 02:09:25,999 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-03facd8bcdc8558f2/sem (recursive=False)
2025-10-07 02:09:25,999 - util.py[DEBUG]: Reading from /var/lib/cloud/instances/i-03facd8bcdc8558f2/datasource (quiet=False)
2025-10-07 02:09:25,999 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-03facd8bcdc8558f2/datasource - wb: [644] 29 bytes
2025-10-07 02:09:26,000 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-03facd8bcdc8558f2/datasource (recursive=False)
2025-10-07 02:09:26,001 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-03facd8bcdc8558f2/datasource (recursive=False)
2025-10-07 02:09:26,001 - util.py[DEBUG]: Writing to /var/lib/cloud/data/previous-datasource - wb: [644] 29 bytes
2025-10-07 02:09:26,001 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/previous-datasource (recursive=False)
2025-10-07 02:09:26,002 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/previous-datasource (recursive=False)
2025-10-07 02:09:26,002 - util.py[DEBUG]: Reading from /var/lib/cloud/data/instance-id (quiet=False)
2025-10-07 02:09:26,002 - stages.py[DEBUG]: previous iid found to be NO_PREVIOUS_INSTANCE_ID
2025-10-07 02:09:26,002 - util.py[DEBUG]: Writing to /var/lib/cloud/data/instance-id - wb: [644] 20 bytes
2025-10-07 02:09:26,003 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/instance-id (recursive=False)
2025-10-07 02:09:26,003 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/instance-id (recursive=False)
2025-10-07 02:09:26,004 - util.py[DEBUG]: Writing to /run/cloud-init/.instance-id - wb: [644] 20 bytes
2025-10-07 02:09:26,004 - util.py[DEBUG]: Restoring selinux mode for /run/cloud-init/.instance-id (recursive=False)
2025-10-07 02:09:26,004 - util.py[DEBUG]: Restoring selinux mode for /run/cloud-init/.instance-id (recursive=False)
2025-10-07 02:09:26,004 - util.py[DEBUG]: Writing to /var/lib/cloud/data/previous-instance-id - wb: [644] 24 bytes
2025-10-07 02:09:26,005 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/previous-instance-id (recursive=False)
2025-10-07 02:09:26,006 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/previous-instance-id (recursive=False)
2025-10-07 02:09:26,006 - util.py[DEBUG]: Writing to /var/lib/cloud/instance/obj.pkl - wb: [400] 12608 bytes
2025-10-07 02:09:26,007 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-03facd8bcdc8558f2/obj.pkl (recursive=False)
2025-10-07 02:09:26,007 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-03facd8bcdc8558f2/obj.pkl (recursive=False)
2025-10-07 02:09:26,008 - main.py[DEBUG]: [net] init will now be targeting instance id: i-03facd8bcdc8558f2. new=True
2025-10-07 02:09:26,008 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg (quiet=False)
2025-10-07 02:09:26,008 - util.py[DEBUG]: Read 2553 bytes from /etc/cloud/cloud.cfg
2025-10-07 02:09:26,008 - util.py[DEBUG]: Attempting to load yaml from string of length 2553 with allowed root types (<class 'dict'>,)
2025-10-07 02:09:26,015 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/40_selinux-reboot.cfg (quiet=False)
2025-10-07 02:09:26,015 - util.py[DEBUG]: Read 174 bytes from /etc/cloud/cloud.cfg.d/40_selinux-reboot.cfg
2025-10-07 02:09:26,015 - util.py[DEBUG]: Attempting to load yaml from string of length 174 with allowed root types (<class 'dict'>,)
2025-10-07 02:09:26,016 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/10_aws_dnfvars.cfg (quiet=False)
2025-10-07 02:09:26,016 - util.py[DEBUG]: Read 591 bytes from /etc/cloud/cloud.cfg.d/10_aws_dnfvars.cfg
2025-10-07 02:09:26,016 - util.py[DEBUG]: Attempting to load yaml from string of length 591 with allowed root types (<class 'dict'>,)
2025-10-07 02:09:26,017 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/05_logging.cfg (quiet=False)
2025-10-07 02:09:26,017 - util.py[DEBUG]: Read 2070 bytes from /etc/cloud/cloud.cfg.d/05_logging.cfg
2025-10-07 02:09:26,017 - util.py[DEBUG]: Attempting to load yaml from string of length 2070 with allowed root types (<class 'dict'>,)
2025-10-07 02:09:26,020 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/01_amazon-ec2.cfg (quiet=False)
2025-10-07 02:09:26,020 - util.py[DEBUG]: Read 237 bytes from /etc/cloud/cloud.cfg.d/01_amazon-ec2.cfg
2025-10-07 02:09:26,020 - util.py[DEBUG]: Attempting to load yaml from string of length 237 with allowed root types (<class 'dict'>,)
2025-10-07 02:09:26,022 - util.py[DEBUG]: Reading from /run/cloud-init/cloud.cfg (quiet=False)
2025-10-07 02:09:26,022 - util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<class 'dict'>,)
2025-10-07 02:09:26,022 - util.py[DEBUG]: loaded blob returned None, returning default.
2025-10-07 02:09:26,023 - util.py[DEBUG]: Reading from /sys/class/net/ens5/address (quiet=False)
2025-10-07 02:09:26,023 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/ens5/address
2025-10-07 02:09:26,023 - util.py[DEBUG]: Reading from /sys/class/net/lo/address (quiet=False)
2025-10-07 02:09:26,023 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/lo/address
2025-10-07 02:09:26,024 - util.py[DEBUG]: Reading from /sys/class/net/ens5/name_assign_type (quiet=False)
2025-10-07 02:09:26,024 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/ens5/name_assign_type
2025-10-07 02:09:26,024 - util.py[DEBUG]: Reading from /sys/class/net/ens5/address (quiet=False)
2025-10-07 02:09:26,024 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/ens5/address
2025-10-07 02:09:26,024 - util.py[DEBUG]: Reading from /sys/class/net/ens5/carrier (quiet=False)
2025-10-07 02:09:26,024 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/ens5/carrier
2025-10-07 02:09:26,024 - util.py[DEBUG]: Reading from /sys/class/net/ens5/addr_assign_type (quiet=False)
2025-10-07 02:09:26,024 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/ens5/addr_assign_type
2025-10-07 02:09:26,024 - util.py[DEBUG]: Reading from /sys/class/net/ens5/uevent (quiet=False)
2025-10-07 02:09:26,024 - util.py[DEBUG]: Read 25 bytes from /sys/class/net/ens5/uevent
2025-10-07 02:09:26,025 - util.py[DEBUG]: Reading from /sys/class/net/ens5/address (quiet=False)
2025-10-07 02:09:26,025 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/ens5/address
2025-10-07 02:09:26,025 - __init__.py[DEBUG]: ovs-vsctl not in PATH; not detecting Open vSwitch interfaces
2025-10-07 02:09:26,025 - util.py[DEBUG]: Reading from /sys/class/net/ens5/device/device (quiet=False)
2025-10-07 02:09:26,025 - util.py[DEBUG]: Read 7 bytes from /sys/class/net/ens5/device/device
2025-10-07 02:09:26,025 - util.py[DEBUG]: Reading from /sys/class/net/lo/addr_assign_type (quiet=False)
2025-10-07 02:09:26,025 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/lo/addr_assign_type
2025-10-07 02:09:26,025 - util.py[DEBUG]: Reading from /sys/class/net/lo/uevent (quiet=False)
2025-10-07 02:09:26,025 - util.py[DEBUG]: Read 23 bytes from /sys/class/net/lo/uevent
2025-10-07 02:09:26,025 - util.py[DEBUG]: Reading from /sys/class/net/lo/address (quiet=False)
2025-10-07 02:09:26,025 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/lo/address
2025-10-07 02:09:26,025 - util.py[DEBUG]: Reading from /sys/class/net/lo/device/device (quiet=False)
2025-10-07 02:09:26,025 - util.py[DEBUG]: Reading from /sys/class/net/ens5/type (quiet=False)
2025-10-07 02:09:26,025 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/ens5/type
2025-10-07 02:09:26,025 - util.py[DEBUG]: Reading from /sys/class/net/lo/type (quiet=False)
2025-10-07 02:09:26,025 - util.py[DEBUG]: Read 4 bytes from /sys/class/net/lo/type
2025-10-07 02:09:26,025 - stages.py[DEBUG]: network config disabled by system_cfg
2025-10-07 02:09:26,025 - stages.py[INFO]: network config is disabled by system_cfg
2025-10-07 02:09:26,025 - handlers.py[DEBUG]: start: init-network/setup-datasource: setting up datasource
2025-10-07 02:09:26,026 - handlers.py[DEBUG]: finish: init-network/setup-datasource: SUCCESS: setting up datasource
2025-10-07 02:09:26,026 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-03facd8bcdc8558f2/user-data.txt - wb: [600] 2480 bytes
2025-10-07 02:09:26,026 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-03facd8bcdc8558f2/user-data.txt (recursive=False)
2025-10-07 02:09:26,027 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-03facd8bcdc8558f2/user-data.txt (recursive=False)
2025-10-07 02:09:26,028 - util.py[DEBUG]: Attempting to load yaml from string of length 104 with allowed root types (<class 'dict'>,)
2025-10-07 02:09:26,031 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-03facd8bcdc8558f2/user-data.txt.i - wb: [600] 2502 bytes
2025-10-07 02:09:26,032 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-03facd8bcdc8558f2/user-data.txt.i (recursive=False)
2025-10-07 02:09:26,033 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-03facd8bcdc8558f2/user-data.txt.i (recursive=False)
2025-10-07 02:09:26,033 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-03facd8bcdc8558f2/vendor-data.txt - wb: [600] 0 bytes
2025-10-07 02:09:26,034 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-03facd8bcdc8558f2/vendor-data.txt (recursive=False)
2025-10-07 02:09:26,035 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-03facd8bcdc8558f2/vendor-data.txt (recursive=False)
2025-10-07 02:09:26,036 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-03facd8bcdc8558f2/vendor-data.txt.i - wb: [600] 308 bytes
2025-10-07 02:09:26,036 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-03facd8bcdc8558f2/vendor-data.txt.i (recursive=False)
2025-10-07 02:09:26,037 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-03facd8bcdc8558f2/vendor-data.txt.i (recursive=False)
2025-10-07 02:09:26,037 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-03facd8bcdc8558f2/vendor-data2.txt - wb: [600] 0 bytes
2025-10-07 02:09:26,038 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-03facd8bcdc8558f2/vendor-data2.txt (recursive=False)
2025-10-07 02:09:26,038 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-03facd8bcdc8558f2/vendor-data2.txt (recursive=False)
2025-10-07 02:09:26,040 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-03facd8bcdc8558f2/vendor-data2.txt.i - wb: [600] 308 bytes
2025-10-07 02:09:26,040 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-03facd8bcdc8558f2/vendor-data2.txt.i (recursive=False)
2025-10-07 02:09:26,041 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-03facd8bcdc8558f2/vendor-data2.txt.i (recursive=False)
2025-10-07 02:09:26,042 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.amazon.Distro'>
2025-10-07 02:09:26,042 - cc_set_hostname.py[DEBUG]: Setting the hostname to ip-172-31-7-134.us-east-2.compute.internal (ip-172-31-7-134)
2025-10-07 02:09:26,042 - subp.py[DEBUG]: Running command ['hostnamectl', 'set-hostname', 'ip-172-31-7-134.us-east-2.compute.internal'] with allowed return codes [0] (shell=False, capture=True)
2025-10-07 02:09:26,158 - __init__.py[DEBUG]: Non-persistently setting the system hostname to ip-172-31-7-134.us-east-2.compute.internal
2025-10-07 02:09:26,159 - subp.py[DEBUG]: Running command ['hostname', 'ip-172-31-7-134.us-east-2.compute.internal'] with allowed return codes [0] (shell=False, capture=True)
2025-10-07 02:09:26,163 - atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/set-hostname (via temporary file /var/lib/cloud/data/tmp6u2ube3t) - w: [644] 90 bytes/chars
2025-10-07 02:09:26,164 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-03facd8bcdc8558f2/sem/consume_data - wb: [644] 24 bytes
2025-10-07 02:09:26,165 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-03facd8bcdc8558f2/sem/consume_data (recursive=False)
2025-10-07 02:09:26,166 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-03facd8bcdc8558f2/sem/consume_data (recursive=False)
2025-10-07 02:09:26,167 - helpers.py[DEBUG]: Running consume_data using lock (<FileLock using file '/var/lib/cloud/instances/i-03facd8bcdc8558f2/sem/consume_data'>)
2025-10-07 02:09:26,167 - handlers.py[DEBUG]: start: init-network/consume-user-data: reading and applying user-data
2025-10-07 02:09:26,167 - launch_index.py[DEBUG]: Discarding 0 multipart messages which do not match launch index 0
2025-10-07 02:09:26,168 - stages.py[DEBUG]: Added default handler for {'text/cloud-config', 'text/cloud-config-jsonp'} from CloudConfigPartHandler: [['text/cloud-config', 'text/cloud-config-jsonp']]
2025-10-07 02:09:26,168 - stages.py[DEBUG]: Added default handler for {'text/x-shellscript'} from ShellScriptPartHandler: [['text/x-shellscript']]
2025-10-07 02:09:26,168 - stages.py[DEBUG]: Added default handler for {'text/x-shellscript-per-boot'} from ShellScriptByFreqPartHandler: [['text/x-shellscript-per-boot']]
2025-10-07 02:09:26,168 - stages.py[DEBUG]: Added default handler for {'text/x-shellscript-per-instance'} from ShellScriptByFreqPartHandler: [['text/x-shellscript-per-instance']]
2025-10-07 02:09:26,168 - stages.py[DEBUG]: Added default handler for {'text/x-shellscript-per-once'} from ShellScriptByFreqPartHandler: [['text/x-shellscript-per-once']]
2025-10-07 02:09:26,168 - stages.py[DEBUG]: Added default handler for {'text/cloud-boothook'} from BootHookPartHandler: [['text/cloud-boothook']]
2025-10-07 02:09:26,168 - stages.py[DEBUG]: Added default handler for {'text/jinja2'} from JinjaTemplatePartHandler: [['text/jinja2']]
2025-10-07 02:09:26,168 - __init__.py[DEBUG]: Calling handler CloudConfigPartHandler: [['text/cloud-config', 'text/cloud-config-jsonp']] (__begin__, None, 3) with frequency once-per-instance
2025-10-07 02:09:26,168 - __init__.py[DEBUG]: Calling handler ShellScriptPartHandler: [['text/x-shellscript']] (__begin__, None, 2) with frequency once-per-instance
2025-10-07 02:09:26,168 - __init__.py[DEBUG]: Calling handler ShellScriptByFreqPartHandler: [['text/x-shellscript-per-boot']] (__begin__, None, 2) with frequency once-per-instance
2025-10-07 02:09:26,168 - __init__.py[DEBUG]: Calling handler ShellScriptByFreqPartHandler: [['text/x-shellscript-per-instance']] (__begin__, None, 2) with frequency once-per-instance
2025-10-07 02:09:26,168 - __init__.py[DEBUG]: Calling handler ShellScriptByFreqPartHandler: [['text/x-shellscript-per-once']] (__begin__, None, 2) with frequency once-per-instance
2025-10-07 02:09:26,168 - __init__.py[DEBUG]: Calling handler BootHookPartHandler: [['text/cloud-boothook']] (__begin__, None, 2) with frequency once-per-instance
2025-10-07 02:09:26,169 - __init__.py[DEBUG]: Calling handler JinjaTemplatePartHandler: [['text/jinja2']] (__begin__, None, 3) with frequency once-per-instance
2025-10-07 02:09:26,169 - __init__.py[DEBUG]: {'Content-Type': 'text/cloud-config; charset="us-ascii"', 'MIME-Version': '1.0', 'Content-Transfer-Encoding': '7bit', 'Content-Disposition': 'attachment; filename="cloud-config.txt"'}
2025-10-07 02:09:26,169 - __init__.py[DEBUG]: Calling handler CloudConfigPartHandler: [['text/cloud-config', 'text/cloud-config-jsonp']] (text/cloud-config, cloud-config.txt, 3) with frequency once-per-instance
2025-10-07 02:09:26,169 - util.py[DEBUG]: Attempting to load yaml from string of length 104 with allowed root types (<class 'dict'>,)
2025-10-07 02:09:26,170 - cloud_config.py[DEBUG]: Merging by applying [('dict', ['replace']), ('list', []), ('str', [])]
2025-10-07 02:09:26,170 - __init__.py[DEBUG]: {'Content-Type': 'text/x-shellscript; charset="us-ascii"', 'MIME-Version': '1.0', 'Content-Transfer-Encoding': '7bit', 'Content-Disposition': 'attachment; filename="user-data.txt"'}
2025-10-07 02:09:26,170 - __init__.py[DEBUG]: Calling handler ShellScriptPartHandler: [['text/x-shellscript']] (text/x-shellscript, user-data.txt, 2) with frequency once-per-instance
2025-10-07 02:09:26,170 - util.py[DEBUG]: Writing to /var/lib/cloud/instance/scripts/user-data.txt - wb: [700] 1831 bytes
2025-10-07 02:09:26,171 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-03facd8bcdc8558f2/scripts/user-data.txt (recursive=False)
2025-10-07 02:09:26,172 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-03facd8bcdc8558f2/scripts/user-data.txt (recursive=False)
2025-10-07 02:09:26,172 - __init__.py[DEBUG]: Calling handler CloudConfigPartHandler: [['text/cloud-config', 'text/cloud-config-jsonp']] (__end__, None, 3) with frequency once-per-instance
2025-10-07 02:09:26,173 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-03facd8bcdc8558f2/cloud-config.txt - wb: [600] 154 bytes
2025-10-07 02:09:26,173 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-03facd8bcdc8558f2/cloud-config.txt (recursive=False)
2025-10-07 02:09:26,174 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-03facd8bcdc8558f2/cloud-config.txt (recursive=False)
2025-10-07 02:09:26,175 - __init__.py[DEBUG]: Calling handler ShellScriptPartHandler: [['text/x-shellscript']] (__end__, None, 2) with frequency once-per-instance
2025-10-07 02:09:26,175 - __init__.py[DEBUG]: Calling handler ShellScriptByFreqPartHandler: [['text/x-shellscript-per-boot']] (__end__, None, 2) with frequency once-per-instance
2025-10-07 02:09:26,175 - __init__.py[DEBUG]: Calling handler ShellScriptByFreqPartHandler: [['text/x-shellscript-per-instance']] (__end__, None, 2) with frequency once-per-instance
2025-10-07 02:09:26,175 - __init__.py[DEBUG]: Calling handler ShellScriptByFreqPartHandler: [['text/x-shellscript-per-once']] (__end__, None, 2) with frequency once-per-instance
2025-10-07 02:09:26,175 - __init__.py[DEBUG]: Calling handler BootHookPartHandler: [['text/cloud-boothook']] (__end__, None, 2) with frequency once-per-instance
2025-10-07 02:09:26,175 - __init__.py[DEBUG]: Calling handler JinjaTemplatePartHandler: [['text/jinja2']] (__end__, None, 3) with frequency once-per-instance
2025-10-07 02:09:26,175 - handlers.py[DEBUG]: finish: init-network/consume-user-data: SUCCESS: reading and applying user-data
2025-10-07 02:09:26,175 - handlers.py[DEBUG]: start: init-network/consume-vendor-data: reading and applying vendor-data
2025-10-07 02:09:26,175 - stages.py[DEBUG]: no vendordata from datasource
2025-10-07 02:09:26,175 - handlers.py[DEBUG]: finish: init-network/consume-vendor-data: SUCCESS: reading and applying vendor-data
2025-10-07 02:09:26,175 - handlers.py[DEBUG]: start: init-network/consume-vendor-data2: reading and applying vendor-data2
2025-10-07 02:09:26,175 - stages.py[DEBUG]: no vendordata2 from datasource
2025-10-07 02:09:26,175 - handlers.py[DEBUG]: finish: init-network/consume-vendor-data2: SUCCESS: reading and applying vendor-data2
2025-10-07 02:09:26,175 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg (quiet=False)
2025-10-07 02:09:26,175 - util.py[DEBUG]: Read 2553 bytes from /etc/cloud/cloud.cfg
2025-10-07 02:09:26,175 - util.py[DEBUG]: Attempting to load yaml from string of length 2553 with allowed root types (<class 'dict'>,)
2025-10-07 02:09:26,182 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/40_selinux-reboot.cfg (quiet=False)
2025-10-07 02:09:26,182 - util.py[DEBUG]: Read 174 bytes from /etc/cloud/cloud.cfg.d/40_selinux-reboot.cfg
2025-10-07 02:09:26,183 - util.py[DEBUG]: Attempting to load yaml from string of length 174 with allowed root types (<class 'dict'>,)
2025-10-07 02:09:26,183 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/10_aws_dnfvars.cfg (quiet=False)
2025-10-07 02:09:26,183 - util.py[DEBUG]: Read 591 bytes from /etc/cloud/cloud.cfg.d/10_aws_dnfvars.cfg
2025-10-07 02:09:26,183 - util.py[DEBUG]: Attempting to load yaml from string of length 591 with allowed root types (<class 'dict'>,)
2025-10-07 02:09:26,185 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/05_logging.cfg (quiet=False)
2025-10-07 02:09:26,185 - util.py[DEBUG]: Read 2070 bytes from /etc/cloud/cloud.cfg.d/05_logging.cfg
2025-10-07 02:09:26,185 - util.py[DEBUG]: Attempting to load yaml from string of length 2070 with allowed root types (<class 'dict'>,)
2025-10-07 02:09:26,188 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/01_amazon-ec2.cfg (quiet=False)
2025-10-07 02:09:26,188 - util.py[DEBUG]: Read 237 bytes from /etc/cloud/cloud.cfg.d/01_amazon-ec2.cfg
2025-10-07 02:09:26,188 - util.py[DEBUG]: Attempting to load yaml from string of length 237 with allowed root types (<class 'dict'>,)
2025-10-07 02:09:26,189 - util.py[DEBUG]: Reading from /run/cloud-init/cloud.cfg (quiet=False)
2025-10-07 02:09:26,190 - util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<class 'dict'>,)
2025-10-07 02:09:26,190 - util.py[DEBUG]: loaded blob returned None, returning default.
2025-10-07 02:09:26,190 - util.py[DEBUG]: Reading from /var/lib/cloud/instance/cloud-config.txt (quiet=False)
2025-10-07 02:09:26,190 - util.py[DEBUG]: Read 154 bytes from /var/lib/cloud/instance/cloud-config.txt
2025-10-07 02:09:26,190 - util.py[DEBUG]: Attempting to load yaml from string of length 154 with allowed root types (<class 'dict'>,)
2025-10-07 02:09:26,191 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-10-07 02:09:26,191 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-10-07 02:09:26,272 - util.py[DEBUG]: Reading from /var/lib/cloud/instance/cloud-config.txt (quiet=False)
2025-10-07 02:09:26,272 - util.py[DEBUG]: Read 154 bytes from /var/lib/cloud/instance/cloud-config.txt
2025-10-07 02:09:26,272 - util.py[DEBUG]: Attempting to load yaml from string of length 154 with allowed root types (<class 'dict'>,)
2025-10-07 02:09:26,275 - handlers.py[DEBUG]: start: init-network/activate-datasource: activating datasource
2025-10-07 02:09:26,276 - util.py[DEBUG]: Writing to /var/lib/cloud/instance/obj.pkl - wb: [400] 16787 bytes
2025-10-07 02:09:26,277 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-03facd8bcdc8558f2/obj.pkl (recursive=False)
2025-10-07 02:09:26,278 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-03facd8bcdc8558f2/obj.pkl (recursive=False)
2025-10-07 02:09:26,279 - handlers.py[DEBUG]: finish: init-network/activate-datasource: SUCCESS: activating datasource
2025-10-07 02:09:26,279 - main.py[DEBUG]: no di_report found in config.
2025-10-07 02:09:26,287 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-10-07 02:09:26,288 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-10-07 02:09:26,290 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-10-07 02:09:26,291 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-10-07 02:09:26,293 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-10-07 02:09:26,293 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-10-07 02:09:26,296 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-10-07 02:09:26,296 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-10-07 02:09:26,298 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-10-07 02:09:26,298 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-10-07 02:09:26,302 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-10-07 02:09:26,302 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-10-07 02:09:26,305 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-10-07 02:09:26,305 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-10-07 02:09:26,309 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-10-07 02:09:26,309 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-10-07 02:09:26,311 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-10-07 02:09:26,312 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-10-07 02:09:26,314 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-10-07 02:09:26,314 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-10-07 02:09:26,316 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-10-07 02:09:26,316 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-10-07 02:09:26,318 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-10-07 02:09:26,319 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-10-07 02:09:26,320 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-10-07 02:09:26,321 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-10-07 02:09:26,323 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-10-07 02:09:26,323 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-10-07 02:09:26,326 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-10-07 02:09:26,326 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-10-07 02:09:26,329 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-10-07 02:09:26,329 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-10-07 02:09:26,331 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.amazon.Distro'>
2025-10-07 02:09:26,332 - modules.py[DEBUG]: Running module migrator (<module 'cloudinit.config.cc_migrator' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_migrator.py'>) with frequency always
2025-10-07 02:09:26,332 - handlers.py[DEBUG]: start: init-network/config-migrator: running config-migrator with frequency always
2025-10-07 02:09:26,332 - helpers.py[DEBUG]: Running config-migrator using lock (<cloudinit.helpers.DummyLock object at 0x7f173968f910>)
2025-10-07 02:09:26,332 - cc_migrator.py[DEBUG]: Migrated 0 semaphore files to there canonicalized names
2025-10-07 02:09:26,332 - handlers.py[DEBUG]: finish: init-network/config-migrator: SUCCESS: config-migrator ran successfully
2025-10-07 02:09:26,332 - modules.py[DEBUG]: Running module seed_random (<module 'cloudinit.config.cc_seed_random' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_seed_random.py'>) with frequency once-per-instance
2025-10-07 02:09:26,332 - handlers.py[DEBUG]: start: init-network/config-seed_random: running config-seed_random with frequency once-per-instance
2025-10-07 02:09:26,332 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-03facd8bcdc8558f2/sem/config_seed_random - wb: [644] 25 bytes
2025-10-07 02:09:26,333 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-03facd8bcdc8558f2/sem/config_seed_random (recursive=False)
2025-10-07 02:09:26,334 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-03facd8bcdc8558f2/sem/config_seed_random (recursive=False)
2025-10-07 02:09:26,334 - helpers.py[DEBUG]: Running config-seed_random using lock (<FileLock using file '/var/lib/cloud/instances/i-03facd8bcdc8558f2/sem/config_seed_random'>)
2025-10-07 02:09:26,334 - cc_seed_random.py[DEBUG]: no command provided
2025-10-07 02:09:26,334 - handlers.py[DEBUG]: finish: init-network/config-seed_random: SUCCESS: config-seed_random ran successfully
2025-10-07 02:09:26,334 - modules.py[DEBUG]: Running module bootcmd (<module 'cloudinit.config.cc_bootcmd' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_bootcmd.py'>) with frequency always
2025-10-07 02:09:26,335 - handlers.py[DEBUG]: start: init-network/config-bootcmd: running config-bootcmd with frequency always
2025-10-07 02:09:26,335 - helpers.py[DEBUG]: Running config-bootcmd using lock (<cloudinit.helpers.DummyLock object at 0x7f173968f910>)
2025-10-07 02:09:26,335 - cc_bootcmd.py[DEBUG]: Skipping module named bootcmd, no 'bootcmd' key in configuration
2025-10-07 02:09:26,335 - handlers.py[DEBUG]: finish: init-network/config-bootcmd: SUCCESS: config-bootcmd ran successfully
2025-10-07 02:09:26,335 - modules.py[DEBUG]: Running module write-files (<module 'cloudinit.config.cc_write_files' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_write_files.py'>) with frequency once-per-instance
2025-10-07 02:09:26,335 - handlers.py[DEBUG]: start: init-network/config-write-files: running config-write-files with frequency once-per-instance
2025-10-07 02:09:26,335 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-03facd8bcdc8558f2/sem/config_write_files - wb: [644] 25 bytes
2025-10-07 02:09:26,335 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-03facd8bcdc8558f2/sem/config_write_files (recursive=False)
2025-10-07 02:09:26,336 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-03facd8bcdc8558f2/sem/config_write_files (recursive=False)
2025-10-07 02:09:26,337 - helpers.py[DEBUG]: Running config-write-files using lock (<FileLock using file '/var/lib/cloud/instances/i-03facd8bcdc8558f2/sem/config_write_files'>)
2025-10-07 02:09:26,337 - cc_write_files.py[DEBUG]: Skipping module named write-files, no/empty 'write_files' key in configuration
2025-10-07 02:09:26,337 - handlers.py[DEBUG]: finish: init-network/config-write-files: SUCCESS: config-write-files ran successfully
2025-10-07 02:09:26,337 - modules.py[DEBUG]: Running module write-metadata (<module 'cloudinit.config.cc_write_metadata' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_write_metadata.py'>) with frequency once-per-instance
2025-10-07 02:09:26,337 - handlers.py[DEBUG]: start: init-network/config-write-metadata: running config-write-metadata with frequency once-per-instance
2025-10-07 02:09:26,337 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-03facd8bcdc8558f2/sem/config_write_metadata - wb: [644] 24 bytes
2025-10-07 02:09:26,337 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-03facd8bcdc8558f2/sem/config_write_metadata (recursive=False)
2025-10-07 02:09:26,338 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-03facd8bcdc8558f2/sem/config_write_metadata (recursive=False)
2025-10-07 02:09:26,338 - helpers.py[DEBUG]: Running config-write-metadata using lock (<FileLock using file '/var/lib/cloud/instances/i-03facd8bcdc8558f2/sem/config_write_metadata'>)
2025-10-07 02:09:26,339 - util.py[DEBUG]: Writing to /etc/dnf/vars/awsregion - wb: [644] 9 bytes
2025-10-07 02:09:26,341 - util.py[DEBUG]: Restoring selinux mode for /etc/dnf/vars/awsregion (recursive=False)
2025-10-07 02:09:26,341 - util.py[DEBUG]: Restoring selinux mode for /etc/dnf/vars/awsregion (recursive=False)
2025-10-07 02:09:26,342 - util.py[DEBUG]: Changing the ownership of /etc/dnf/vars/awsregion to 0:0
2025-10-07 02:09:26,342 - util.py[DEBUG]: Writing to /etc/dnf/vars/awsdomain - wb: [644] 13 bytes
2025-10-07 02:09:26,342 - util.py[DEBUG]: Restoring selinux mode for /etc/dnf/vars/awsdomain (recursive=False)
2025-10-07 02:09:26,343 - util.py[DEBUG]: Restoring selinux mode for /etc/dnf/vars/awsdomain (recursive=False)
2025-10-07 02:09:26,343 - util.py[DEBUG]: Changing the ownership of /etc/dnf/vars/awsdomain to 0:0
2025-10-07 02:09:26,343 - handlers.py[DEBUG]: finish: init-network/config-write-metadata: SUCCESS: config-write-metadata ran successfully
2025-10-07 02:09:26,343 - modules.py[DEBUG]: Running module growpart (<module 'cloudinit.config.cc_growpart' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_growpart.py'>) with frequency always
2025-10-07 02:09:26,343 - handlers.py[DEBUG]: start: init-network/config-growpart: running config-growpart with frequency always
2025-10-07 02:09:26,343 - helpers.py[DEBUG]: Running config-growpart using lock (<cloudinit.helpers.DummyLock object at 0x7f173968fb20>)
2025-10-07 02:09:26,343 - cc_growpart.py[DEBUG]: No 'growpart' entry in cfg.  Using default: {'mode': 'auto', 'devices': ['/'], 'ignore_growroot_disabled': False}
2025-10-07 02:09:26,343 - subp.py[DEBUG]: Running command ['growpart', '--help'] with allowed return codes [0] (shell=False, capture=True)
2025-10-07 02:09:26,360 - util.py[DEBUG]: Reading from /proc/1449/mountinfo (quiet=False)
2025-10-07 02:09:26,360 - util.py[DEBUG]: Read 2939 bytes from /proc/1449/mountinfo
2025-10-07 02:09:26,361 - util.py[DEBUG]: Reading from /sys/class/block/nvme0n1p1/partition (quiet=False)
2025-10-07 02:09:26,361 - util.py[DEBUG]: Read 2 bytes from /sys/class/block/nvme0n1p1/partition
2025-10-07 02:09:26,361 - util.py[DEBUG]: Reading from /sys/devices/pci0000:00/0000:00:04.0/nvme/nvme0/nvme0n1/dev (quiet=False)
2025-10-07 02:09:26,361 - util.py[DEBUG]: Read 6 bytes from /sys/devices/pci0000:00/0000:00:04.0/nvme/nvme0/nvme0n1/dev
2025-10-07 02:09:26,362 - subp.py[DEBUG]: Running command ['growpart', '--dry-run', '/dev/nvme0n1', '1'] with allowed return codes [0] (shell=False, capture=True)
2025-10-07 02:09:26,423 - util.py[DEBUG]: resize_devices took 0.063 seconds
2025-10-07 02:09:26,423 - cc_growpart.py[DEBUG]: '/' NOCHANGE: no change necessary (/dev/nvme0n1, 1)
2025-10-07 02:09:26,423 - handlers.py[DEBUG]: finish: init-network/config-growpart: SUCCESS: config-growpart ran successfully
2025-10-07 02:09:26,423 - modules.py[DEBUG]: Running module resizefs (<module 'cloudinit.config.cc_resizefs' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_resizefs.py'>) with frequency always
2025-10-07 02:09:26,424 - handlers.py[DEBUG]: start: init-network/config-resizefs: running config-resizefs with frequency always
2025-10-07 02:09:26,424 - helpers.py[DEBUG]: Running config-resizefs using lock (<cloudinit.helpers.DummyLock object at 0x7f173968f910>)
2025-10-07 02:09:26,424 - util.py[DEBUG]: Reading from /proc/1449/mountinfo (quiet=False)
2025-10-07 02:09:26,424 - util.py[DEBUG]: Read 2939 bytes from /proc/1449/mountinfo
2025-10-07 02:09:26,424 - cc_resizefs.py[DEBUG]: resize_info: dev=/dev/nvme0n1p1 mnt_point=/ path=/
2025-10-07 02:09:26,424 - cc_resizefs.py[DEBUG]: Resizing / (xfs) using xfs_growfs /
2025-10-07 02:09:26,425 - util.py[DEBUG]: Forked child 1570 who will run callback log_time
2025-10-07 02:09:26,426 - cc_resizefs.py[DEBUG]: Resizing (via forking) root filesystem (type=xfs, val=noblock)
2025-10-07 02:09:26,426 - subp.py[DEBUG]: Running command ('xfs_growfs', '/') with allowed return codes [0] (shell=False, capture=True)
2025-10-07 02:09:26,426 - handlers.py[DEBUG]: finish: init-network/config-resizefs: SUCCESS: config-resizefs ran successfully
2025-10-07 02:09:26,426 - modules.py[DEBUG]: Running module disk_setup (<module 'cloudinit.config.cc_disk_setup' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_disk_setup.py'>) with frequency once-per-instance
2025-10-07 02:09:26,427 - handlers.py[DEBUG]: start: init-network/config-disk_setup: running config-disk_setup with frequency once-per-instance
2025-10-07 02:09:26,427 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-03facd8bcdc8558f2/sem/config_disk_setup - wb: [644] 25 bytes
2025-10-07 02:09:26,429 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-03facd8bcdc8558f2/sem/config_disk_setup (recursive=False)
2025-10-07 02:09:26,431 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-03facd8bcdc8558f2/sem/config_disk_setup (recursive=False)
2025-10-07 02:09:26,431 - helpers.py[DEBUG]: Running config-disk_setup using lock (<FileLock using file '/var/lib/cloud/instances/i-03facd8bcdc8558f2/sem/config_disk_setup'>)
2025-10-07 02:09:26,431 - handlers.py[DEBUG]: finish: init-network/config-disk_setup: SUCCESS: config-disk_setup ran successfully
2025-10-07 02:09:26,431 - modules.py[DEBUG]: Running module mounts (<module 'cloudinit.config.cc_mounts' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_mounts.py'>) with frequency once-per-instance
2025-10-07 02:09:26,431 - handlers.py[DEBUG]: start: init-network/config-mounts: running config-mounts with frequency once-per-instance
2025-10-07 02:09:26,431 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-03facd8bcdc8558f2/sem/config_mounts - wb: [644] 24 bytes
2025-10-07 02:09:26,432 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-03facd8bcdc8558f2/sem/config_mounts (recursive=False)
2025-10-07 02:09:26,433 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-03facd8bcdc8558f2/sem/config_mounts (recursive=False)
2025-10-07 02:09:26,433 - helpers.py[DEBUG]: Running config-mounts using lock (<FileLock using file '/var/lib/cloud/instances/i-03facd8bcdc8558f2/sem/config_mounts'>)
2025-10-07 02:09:26,433 - cc_mounts.py[DEBUG]: mounts configuration is []
2025-10-07 02:09:26,433 - util.py[DEBUG]: Reading from /etc/fstab (quiet=False)
2025-10-07 02:09:26,433 - util.py[DEBUG]: Read 217 bytes from /etc/fstab
2025-10-07 02:09:26,434 - cc_mounts.py[DEBUG]: Attempting to determine the real name of ephemeral0
2025-10-07 02:09:26,434 - DataSourceEc2.py[DEBUG]: Unable to convert ephemeral0 to a device
2025-10-07 02:09:26,434 - cc_mounts.py[DEBUG]: changed default device ephemeral0 => None
2025-10-07 02:09:26,434 - cc_mounts.py[DEBUG]: Ignoring nonexistent default named mount ephemeral0
2025-10-07 02:09:26,434 - cc_mounts.py[DEBUG]: Attempting to determine the real name of swap
2025-10-07 02:09:26,434 - DataSourceEc2.py[DEBUG]: Unable to convert swap to a device
2025-10-07 02:09:26,434 - cc_mounts.py[DEBUG]: changed default device swap => None
2025-10-07 02:09:26,434 - cc_mounts.py[DEBUG]: Ignoring nonexistent default named mount swap
2025-10-07 02:09:26,434 - cc_mounts.py[DEBUG]: no need to setup swap
2025-10-07 02:09:26,434 - cc_mounts.py[DEBUG]: No modifications to fstab needed
2025-10-07 02:09:26,434 - handlers.py[DEBUG]: finish: init-network/config-mounts: SUCCESS: config-mounts ran successfully
2025-10-07 02:09:26,434 - modules.py[DEBUG]: Running module set_hostname (<module 'cloudinit.config.cc_set_hostname' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_set_hostname.py'>) with frequency always
2025-10-07 02:09:26,434 - handlers.py[DEBUG]: start: init-network/config-set_hostname: running config-set_hostname with frequency always
2025-10-07 02:09:26,434 - helpers.py[DEBUG]: Running config-set_hostname using lock (<cloudinit.helpers.DummyLock object at 0x7f173968fd00>)
2025-10-07 02:09:26,434 - util.py[DEBUG]: Reading from /var/lib/cloud/data/set-hostname (quiet=False)
2025-10-07 02:09:26,434 - util.py[DEBUG]: Read 90 bytes from /var/lib/cloud/data/set-hostname
2025-10-07 02:09:26,434 - cc_set_hostname.py[DEBUG]: No hostname changes. Skipping set-hostname
2025-10-07 02:09:26,435 - handlers.py[DEBUG]: finish: init-network/config-set_hostname: SUCCESS: config-set_hostname ran successfully
2025-10-07 02:09:26,435 - modules.py[DEBUG]: Running module update_hostname (<module 'cloudinit.config.cc_update_hostname' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_update_hostname.py'>) with frequency always
2025-10-07 02:09:26,435 - handlers.py[DEBUG]: start: init-network/config-update_hostname: running config-update_hostname with frequency always
2025-10-07 02:09:26,435 - helpers.py[DEBUG]: Running config-update_hostname using lock (<cloudinit.helpers.DummyLock object at 0x7f173968fb20>)
2025-10-07 02:09:26,435 - cc_update_hostname.py[DEBUG]: Updating hostname to ip-172-31-7-134.us-east-2.compute.internal (ip-172-31-7-134)
2025-10-07 02:09:26,435 - subp.py[DEBUG]: Running command ['hostname'] with allowed return codes [0] (shell=False, capture=True)
2025-10-07 02:09:26,438 - __init__.py[DEBUG]: Attempting to update hostname to ip-172-31-7-134.us-east-2.compute.internal in 1 files
2025-10-07 02:09:26,438 - util.py[DEBUG]: Writing to /var/lib/cloud/data/previous-hostname - wb: [644] 42 bytes
2025-10-07 02:09:26,439 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/previous-hostname (recursive=False)
2025-10-07 02:09:26,441 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/previous-hostname (recursive=False)
2025-10-07 02:09:26,441 - handlers.py[DEBUG]: finish: init-network/config-update_hostname: SUCCESS: config-update_hostname ran successfully
2025-10-07 02:09:26,441 - modules.py[DEBUG]: Running module update_etc_hosts (<module 'cloudinit.config.cc_update_etc_hosts' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_update_etc_hosts.py'>) with frequency always
2025-10-07 02:09:26,442 - handlers.py[DEBUG]: start: init-network/config-update_etc_hosts: running config-update_etc_hosts with frequency always
2025-10-07 02:09:26,442 - helpers.py[DEBUG]: Running config-update_etc_hosts using lock (<cloudinit.helpers.DummyLock object at 0x7f173968fd00>)
2025-10-07 02:09:26,442 - cc_update_etc_hosts.py[DEBUG]: Configuration option 'manage_etc_hosts' is not set, not managing /etc/hosts in module update_etc_hosts
2025-10-07 02:09:26,442 - handlers.py[DEBUG]: finish: init-network/config-update_etc_hosts: SUCCESS: config-update_etc_hosts ran successfully
2025-10-07 02:09:26,442 - modules.py[DEBUG]: Running module ca-certs (<module 'cloudinit.config.cc_ca_certs' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_ca_certs.py'>) with frequency once-per-instance
2025-10-07 02:09:26,442 - handlers.py[DEBUG]: start: init-network/config-ca-certs: running config-ca-certs with frequency once-per-instance
2025-10-07 02:09:26,442 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-03facd8bcdc8558f2/sem/config_ca_certs - wb: [644] 25 bytes
2025-10-07 02:09:26,443 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-03facd8bcdc8558f2/sem/config_ca_certs (recursive=False)
2025-10-07 02:09:26,443 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-03facd8bcdc8558f2/sem/config_ca_certs (recursive=False)
2025-10-07 02:09:26,444 - helpers.py[DEBUG]: Running config-ca-certs using lock (<FileLock using file '/var/lib/cloud/instances/i-03facd8bcdc8558f2/sem/config_ca_certs'>)
2025-10-07 02:09:26,444 - cc_ca_certs.py[DEBUG]: Skipping module named ca-certs, no 'ca_certs' key in configuration
2025-10-07 02:09:26,444 - handlers.py[DEBUG]: finish: init-network/config-ca-certs: SUCCESS: config-ca-certs ran successfully
2025-10-07 02:09:26,444 - modules.py[DEBUG]: Running module rsyslog (<module 'cloudinit.config.cc_rsyslog' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_rsyslog.py'>) with frequency once-per-instance
2025-10-07 02:09:26,444 - handlers.py[DEBUG]: start: init-network/config-rsyslog: running config-rsyslog with frequency once-per-instance
2025-10-07 02:09:26,444 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-03facd8bcdc8558f2/sem/config_rsyslog - wb: [644] 25 bytes
2025-10-07 02:09:26,445 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-03facd8bcdc8558f2/sem/config_rsyslog (recursive=False)
2025-10-07 02:09:26,446 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-03facd8bcdc8558f2/sem/config_rsyslog (recursive=False)
2025-10-07 02:09:26,446 - helpers.py[DEBUG]: Running config-rsyslog using lock (<FileLock using file '/var/lib/cloud/instances/i-03facd8bcdc8558f2/sem/config_rsyslog'>)
2025-10-07 02:09:26,446 - cc_rsyslog.py[DEBUG]: Skipping module named rsyslog, no 'rsyslog' key in configuration
2025-10-07 02:09:26,446 - handlers.py[DEBUG]: finish: init-network/config-rsyslog: SUCCESS: config-rsyslog ran successfully
2025-10-07 02:09:26,446 - modules.py[DEBUG]: Running module selinux (<module 'cloudinit.config.cc_selinux' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_selinux.py'>) with frequency once-per-instance
2025-10-07 02:09:26,446 - handlers.py[DEBUG]: start: init-network/config-selinux: running config-selinux with frequency once-per-instance
2025-10-07 02:09:26,446 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-03facd8bcdc8558f2/sem/config_selinux - wb: [644] 25 bytes
2025-10-07 02:09:26,447 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-03facd8bcdc8558f2/sem/config_selinux (recursive=False)
2025-10-07 02:09:26,448 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-03facd8bcdc8558f2/sem/config_selinux (recursive=False)
2025-10-07 02:09:26,448 - helpers.py[DEBUG]: Running config-selinux using lock (<FileLock using file '/var/lib/cloud/instances/i-03facd8bcdc8558f2/sem/config_selinux'>)
2025-10-07 02:09:26,454 - cc_selinux.py[DEBUG]: Current SELinux state is enabled
2025-10-07 02:09:26,454 - cc_selinux.py[DEBUG]: Current SELinux mode is permissive
2025-10-07 02:09:26,454 - cc_selinux.py[DEBUG]: Configured SELinux mode is permissive
2025-10-07 02:09:26,454 - cc_selinux.py[DEBUG]: Current SELinux policy is targeted
2025-10-07 02:09:26,454 - cc_selinux.py[DEBUG]: No SELinux configuration, skipping
2025-10-07 02:09:26,454 - handlers.py[DEBUG]: finish: init-network/config-selinux: SUCCESS: config-selinux ran successfully
2025-10-07 02:09:26,454 - modules.py[DEBUG]: Running module users-groups (<module 'cloudinit.config.cc_users_groups' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_users_groups.py'>) with frequency once-per-instance
2025-10-07 02:09:26,455 - handlers.py[DEBUG]: start: init-network/config-users-groups: running config-users-groups with frequency once-per-instance
2025-10-07 02:09:26,455 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-03facd8bcdc8558f2/sem/config_users_groups - wb: [644] 24 bytes
2025-10-07 02:09:26,455 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-03facd8bcdc8558f2/sem/config_users_groups (recursive=False)
2025-10-07 02:09:26,457 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-03facd8bcdc8558f2/sem/config_users_groups (recursive=False)
2025-10-07 02:09:26,457 - helpers.py[DEBUG]: Running config-users-groups using lock (<FileLock using file '/var/lib/cloud/instances/i-03facd8bcdc8558f2/sem/config_users_groups'>)
2025-10-07 02:09:26,458 - __init__.py[INFO]: User ec2-user already exists, skipping.
2025-10-07 02:09:26,458 - subp.py[DEBUG]: Running command ['passwd', '-l', 'ec2-user'] with allowed return codes [0] (shell=False, capture=True)
2025-10-07 02:09:26,462 - util.py[DEBUG]: backgrounded Resizing took 0.036 seconds
2025-10-07 02:09:26,518 - util.py[DEBUG]: Reading from /etc/sudoers (quiet=False)
2025-10-07 02:09:26,528 - util.py[DEBUG]: Read 4375 bytes from /etc/sudoers
2025-10-07 02:09:26,530 - util.py[DEBUG]: Restoring selinux mode for /etc/sudoers.d (recursive=False)
2025-10-07 02:09:26,531 - util.py[DEBUG]: Writing to /etc/sudoers.d/90-cloud-init-users - ab: [None] 59 bytes
2025-10-07 02:09:26,532 - util.py[DEBUG]: Restoring selinux mode for /etc/sudoers.d/90-cloud-init-users (recursive=False)
2025-10-07 02:09:26,532 - handlers.py[DEBUG]: finish: init-network/config-users-groups: SUCCESS: config-users-groups ran successfully
2025-10-07 02:09:26,532 - modules.py[DEBUG]: Running module ssh (<module 'cloudinit.config.cc_ssh' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_ssh.py'>) with frequency once-per-instance
2025-10-07 02:09:26,533 - handlers.py[DEBUG]: start: init-network/config-ssh: running config-ssh with frequency once-per-instance
2025-10-07 02:09:26,533 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-03facd8bcdc8558f2/sem/config_ssh - wb: [644] 25 bytes
2025-10-07 02:09:26,534 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-03facd8bcdc8558f2/sem/config_ssh (recursive=False)
2025-10-07 02:09:26,535 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-03facd8bcdc8558f2/sem/config_ssh (recursive=False)
2025-10-07 02:09:26,535 - helpers.py[DEBUG]: Running config-ssh using lock (<FileLock using file '/var/lib/cloud/instances/i-03facd8bcdc8558f2/sem/config_ssh'>)
2025-10-07 02:09:26,535 - subp.py[DEBUG]: Running command ['ssh-keygen', '-t', 'ed25519', '-N', '', '-f', '/etc/ssh/ssh_host_ed25519_key'] with allowed return codes [0] (shell=False, capture=True)
2025-10-07 02:09:26,549 - util.py[DEBUG]: Restoring selinux mode for /etc/ssh (recursive=True)
2025-10-07 02:09:26,555 - subp.py[DEBUG]: Running command ['ssh-keygen', '-t', 'ecdsa', '-N', '', '-f', '/etc/ssh/ssh_host_ecdsa_key'] with allowed return codes [0] (shell=False, capture=True)
2025-10-07 02:09:26,563 - util.py[DEBUG]: Restoring selinux mode for /etc/ssh (recursive=True)
2025-10-07 02:09:26,568 - util.py[DEBUG]: Reading from /etc/ssh/ssh_host_ed25519_key.pub (quiet=False)
2025-10-07 02:09:26,568 - util.py[DEBUG]: Read 129 bytes from /etc/ssh/ssh_host_ed25519_key.pub
2025-10-07 02:09:26,568 - util.py[DEBUG]: Reading from /etc/ssh/ssh_host_ecdsa_key.pub (quiet=False)
2025-10-07 02:09:26,569 - util.py[DEBUG]: Read 209 bytes from /etc/ssh/ssh_host_ecdsa_key.pub
2025-10-07 02:09:26,569 - util.py[DEBUG]: Reading from /etc/ssh/sshd_config (quiet=False)
2025-10-07 02:09:26,570 - util.py[DEBUG]: Read 3854 bytes from /etc/ssh/sshd_config
2025-10-07 02:09:26,571 - util.py[DEBUG]: Changing the ownership of /home/ec2-user/.ssh to 1000:1000
2025-10-07 02:09:26,571 - util.py[DEBUG]: Restoring selinux mode for /home/ec2-user/.ssh (recursive=False)
2025-10-07 02:09:26,572 - util.py[DEBUG]: Writing to /home/ec2-user/.ssh/authorized_keys - wb: [600] 0 bytes
2025-10-07 02:09:26,572 - util.py[DEBUG]: Restoring selinux mode for /home/ec2-user/.ssh/authorized_keys (recursive=False)
2025-10-07 02:09:26,572 - util.py[DEBUG]: Restoring selinux mode for /home/ec2-user/.ssh/authorized_keys (recursive=False)
2025-10-07 02:09:26,573 - util.py[DEBUG]: Changing the ownership of /home/ec2-user/.ssh/authorized_keys to 1000:1000
2025-10-07 02:09:26,573 - util.py[DEBUG]: Reading from /home/ec2-user/.ssh/authorized_keys (quiet=False)
2025-10-07 02:09:26,573 - util.py[DEBUG]: Read 0 bytes from /home/ec2-user/.ssh/authorized_keys
2025-10-07 02:09:26,573 - util.py[DEBUG]: Writing to /home/ec2-user/.ssh/authorized_keys - wb: [600] 0 bytes
2025-10-07 02:09:26,573 - util.py[DEBUG]: Restoring selinux mode for /home/ec2-user/.ssh/authorized_keys (recursive=False)
2025-10-07 02:09:26,573 - util.py[DEBUG]: Restoring selinux mode for /home/ec2-user/.ssh/authorized_keys (recursive=False)
2025-10-07 02:09:26,573 - util.py[DEBUG]: Restoring selinux mode for /home/ec2-user/.ssh (recursive=True)
2025-10-07 02:09:26,574 - util.py[DEBUG]: Reading from /etc/ssh/sshd_config (quiet=False)
2025-10-07 02:09:26,574 - util.py[DEBUG]: Read 3854 bytes from /etc/ssh/sshd_config
2025-10-07 02:09:26,575 - util.py[DEBUG]: Restoring selinux mode for /root/.ssh (recursive=True)
2025-10-07 02:09:26,576 - util.py[DEBUG]: Writing to /root/.ssh/authorized_keys - wb: [600] 0 bytes
2025-10-07 02:09:26,576 - util.py[DEBUG]: Restoring selinux mode for /root/.ssh/authorized_keys (recursive=False)
2025-10-07 02:09:26,576 - util.py[DEBUG]: Restoring selinux mode for /root/.ssh/authorized_keys (recursive=False)
2025-10-07 02:09:26,577 - util.py[DEBUG]: Changing the ownership of /root/.ssh/authorized_keys to 0:0
2025-10-07 02:09:26,577 - util.py[DEBUG]: Reading from /root/.ssh/authorized_keys (quiet=False)
2025-10-07 02:09:26,577 - util.py[DEBUG]: Read 0 bytes from /root/.ssh/authorized_keys
2025-10-07 02:09:26,577 - util.py[DEBUG]: Writing to /root/.ssh/authorized_keys - wb: [600] 0 bytes
2025-10-07 02:09:26,577 - util.py[DEBUG]: Restoring selinux mode for /root/.ssh/authorized_keys (recursive=False)
2025-10-07 02:09:26,577 - util.py[DEBUG]: Restoring selinux mode for /root/.ssh/authorized_keys (recursive=False)
2025-10-07 02:09:26,577 - util.py[DEBUG]: Restoring selinux mode for /root/.ssh (recursive=True)
2025-10-07 02:09:26,578 - handlers.py[DEBUG]: finish: init-network/config-ssh: SUCCESS: config-ssh ran successfully
2025-10-07 02:09:26,579 - main.py[DEBUG]: Ran 17 modules with 0 failures
2025-10-07 02:09:26,579 - atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/status.json (via temporary file /var/lib/cloud/data/tmp5x7p9lcx) - w: [644] 486 bytes/chars
2025-10-07 02:09:26,579 - util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
2025-10-07 02:09:26,579 - util.py[DEBUG]: Read 10 bytes from /proc/uptime
2025-10-07 02:09:26,579 - util.py[DEBUG]: cloud-init mode 'init' took 1.006 seconds (1.01)
2025-10-07 02:09:26,579 - handlers.py[DEBUG]: finish: init-network: SUCCESS: searching for network datasources
2025-10-07 02:09:27,181 - util.py[DEBUG]: Cloud-init v. 22.2.2 running 'modules:config' at Tue, 07 Oct 2025 02:09:27 +0000. Up 8.74 seconds.
2025-10-07 02:09:27,183 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-10-07 02:09:27,183 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-10-07 02:09:27,186 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-10-07 02:09:27,186 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-10-07 02:09:27,188 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-10-07 02:09:27,188 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-10-07 02:09:27,190 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-10-07 02:09:27,191 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-10-07 02:09:27,193 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-10-07 02:09:27,193 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-10-07 02:09:27,196 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-10-07 02:09:27,196 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-10-07 02:09:27,199 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-10-07 02:09:27,199 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-10-07 02:09:27,202 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-10-07 02:09:27,202 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-10-07 02:09:27,204 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-10-07 02:09:27,204 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-10-07 02:09:27,206 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-10-07 02:09:27,207 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-10-07 02:09:27,208 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.amazon.Distro'>
2025-10-07 02:09:27,209 - modules.py[INFO]: Skipping modules 'ssh-import-id' because they are not verified on distro 'amazon'.  To run anyway, add them to 'unverified_modules' in config.
2025-10-07 02:09:27,209 - modules.py[DEBUG]: Running module keyboard (<module 'cloudinit.config.cc_keyboard' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_keyboard.py'>) with frequency once-per-instance
2025-10-07 02:09:27,209 - handlers.py[DEBUG]: start: modules-config/config-keyboard: running config-keyboard with frequency once-per-instance
2025-10-07 02:09:27,209 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-03facd8bcdc8558f2/sem/config_keyboard - wb: [644] 25 bytes
2025-10-07 02:09:27,212 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-03facd8bcdc8558f2/sem/config_keyboard (recursive=False)
2025-10-07 02:09:27,214 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-03facd8bcdc8558f2/sem/config_keyboard (recursive=False)
2025-10-07 02:09:27,215 - helpers.py[DEBUG]: Running config-keyboard using lock (<FileLock using file '/var/lib/cloud/instances/i-03facd8bcdc8558f2/sem/config_keyboard'>)
2025-10-07 02:09:27,215 - cc_keyboard.py[DEBUG]: Skipping module named keyboard, no 'keyboard' section found
2025-10-07 02:09:27,215 - handlers.py[DEBUG]: finish: modules-config/config-keyboard: SUCCESS: config-keyboard ran successfully
2025-10-07 02:09:27,215 - modules.py[DEBUG]: Running module locale (<module 'cloudinit.config.cc_locale' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_locale.py'>) with frequency once-per-instance
2025-10-07 02:09:27,215 - handlers.py[DEBUG]: start: modules-config/config-locale: running config-locale with frequency once-per-instance
2025-10-07 02:09:27,215 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-03facd8bcdc8558f2/sem/config_locale - wb: [644] 25 bytes
2025-10-07 02:09:27,216 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-03facd8bcdc8558f2/sem/config_locale (recursive=False)
2025-10-07 02:09:27,217 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-03facd8bcdc8558f2/sem/config_locale (recursive=False)
2025-10-07 02:09:27,218 - helpers.py[DEBUG]: Running config-locale using lock (<FileLock using file '/var/lib/cloud/instances/i-03facd8bcdc8558f2/sem/config_locale'>)
2025-10-07 02:09:27,218 - util.py[DEBUG]: Reading from /etc/locale.conf (quiet=False)
2025-10-07 02:09:27,218 - util.py[DEBUG]: Read 17 bytes from /etc/locale.conf
2025-10-07 02:09:27,218 - cc_locale.py[DEBUG]: Setting locale to en_US.UTF-8
2025-10-07 02:09:27,219 - util.py[DEBUG]: Reading from /etc/locale.conf (quiet=False)
2025-10-07 02:09:27,219 - util.py[DEBUG]: Read 17 bytes from /etc/locale.conf
2025-10-07 02:09:27,219 - util.py[DEBUG]: Writing to /etc/locale.conf - wb: [644] 17 bytes
2025-10-07 02:09:27,222 - util.py[DEBUG]: Restoring selinux mode for /etc/locale.conf (recursive=False)
2025-10-07 02:09:27,223 - util.py[DEBUG]: Restoring selinux mode for /etc/locale.conf (recursive=False)
2025-10-07 02:09:27,224 - handlers.py[DEBUG]: finish: modules-config/config-locale: SUCCESS: config-locale ran successfully
2025-10-07 02:09:27,224 - modules.py[DEBUG]: Running module set-passwords (<module 'cloudinit.config.cc_set_passwords' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_set_passwords.py'>) with frequency once-per-instance
2025-10-07 02:09:27,224 - handlers.py[DEBUG]: start: modules-config/config-set-passwords: running config-set-passwords with frequency once-per-instance
2025-10-07 02:09:27,224 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-03facd8bcdc8558f2/sem/config_set_passwords - wb: [644] 24 bytes
2025-10-07 02:09:27,225 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-03facd8bcdc8558f2/sem/config_set_passwords (recursive=False)
2025-10-07 02:09:27,225 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-03facd8bcdc8558f2/sem/config_set_passwords (recursive=False)
2025-10-07 02:09:27,226 - helpers.py[DEBUG]: Running config-set-passwords using lock (<FileLock using file '/var/lib/cloud/instances/i-03facd8bcdc8558f2/sem/config_set_passwords'>)
2025-10-07 02:09:27,226 - subp.py[DEBUG]: Running command ['systemctl', 'status', 'sshd'] with allowed return codes [0] (shell=False, capture=True)
2025-10-07 02:09:27,245 - util.py[DEBUG]: Reading from /etc/ssh/sshd_config (quiet=False)
2025-10-07 02:09:27,245 - util.py[DEBUG]: Read 3854 bytes from /etc/ssh/sshd_config
2025-10-07 02:09:27,245 - ssh_util.py[DEBUG]: line 65: option PasswordAuthentication already set to no
2025-10-07 02:09:27,245 - cc_set_passwords.py[DEBUG]: No need to restart SSH service, PasswordAuthentication not updated.
2025-10-07 02:09:27,246 - handlers.py[DEBUG]: finish: modules-config/config-set-passwords: SUCCESS: config-set-passwords ran successfully
2025-10-07 02:09:27,246 - modules.py[DEBUG]: Running module yum-variables (<module 'cloudinit.config.cc_yum_variables' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_yum_variables.py'>) with frequency once-per-instance
2025-10-07 02:09:27,246 - handlers.py[DEBUG]: start: modules-config/config-yum-variables: running config-yum-variables with frequency once-per-instance
2025-10-07 02:09:27,246 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-03facd8bcdc8558f2/sem/config_yum_variables - wb: [644] 25 bytes
2025-10-07 02:09:27,247 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-03facd8bcdc8558f2/sem/config_yum_variables (recursive=False)
2025-10-07 02:09:27,248 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-03facd8bcdc8558f2/sem/config_yum_variables (recursive=False)
2025-10-07 02:09:27,248 - helpers.py[DEBUG]: Running config-yum-variables using lock (<FileLock using file '/var/lib/cloud/instances/i-03facd8bcdc8558f2/sem/config_yum_variables'>)
2025-10-07 02:09:27,248 - cc_yum_variables.py[INFO]: handling yum-variables
2025-10-07 02:09:27,248 - cc_yum_variables.py[INFO]: cfg = {'cloud_final_modules': [['scripts-user', 'always']], 'repo_releasever': 2023.8, 'repo_upgrade': 'none', 'power_state': {'delay': 'now', 'mode': 'reboot', 'message': 'Rebooting machine to apply SELinux kernel commandline setting', 'condition': 'test -f /run/cloud-init-selinux-reboot'}, 'write_metadata': [{'path': '/etc/dnf/vars/awsregion', 'data': [{'identity': 'region'}, 'default']}, {'path': '/etc/dnf/vars/awsdomain', 'data': [{'metadata': 'services/domain'}, 'amazonaws.com']}], '_log': ['[loggers]\nkeys=root,cloudinit\n\n[handlers]\nkeys=consoleHandler,cloudLogHandler\n\n[formatters]\nkeys=simpleFormatter,arg0Formatter\n\n[logger_root]\nlevel=DEBUG\nhandlers=consoleHandler,cloudLogHandler\n\n[logger_cloudinit]\nlevel=DEBUG\nqualname=cloudinit\nhandlers=\npropagate=1\n\n[handler_consoleHandler]\nclass=StreamHandler\nlevel=WARNING\nformatter=arg0Formatter\nargs=(sys.stderr,)\n\n[formatter_arg0Formatter]\nformat=%(asctime)s - %(filename)s[%(levelname)s]: %(message)s\n\n[formatter_simpleFormatter]\nformat=[CLOUDINIT] %(filename)s[%(levelname)s]: %(message)s\n', "[handler_cloudLogHandler]\nclass=FileHandler\nlevel=DEBUG\nformatter=arg0Formatter\nargs=('/var/log/cloud-init.log', 'a', 'UTF-8')\n", '[handler_cloudLogHandler]\nclass=handlers.SysLogHandler\nlevel=DEBUG\nformatter=simpleFormatter\nargs=("/dev/log", handlers.SysLogHandler.LOG_USER)\n'], 'log_cfgs': [['[loggers]\nkeys=root,cloudinit\n\n[handlers]\nkeys=consoleHandler,cloudLogHandler\n\n[formatters]\nkeys=simpleFormatter,arg0Formatter\n\n[logger_root]\nlevel=DEBUG\nhandlers=consoleHandler,cloudLogHandler\n\n[logger_cloudinit]\nlevel=DEBUG\nqualname=cloudinit\nhandlers=\npropagate=1\n\n[handler_consoleHandler]\nclass=StreamHandler\nlevel=WARNING\nformatter=arg0Formatter\nargs=(sys.stderr,)\n\n[formatter_arg0Formatter]\nformat=%(asctime)s - %(filename)s[%(levelname)s]: %(message)s\n\n[formatter_simpleFormatter]\nformat=[CLOUDINIT] %(filename)s[%(levelname)s]: %(message)s\n', "[handler_cloudLogHandler]\nclass=FileHandler\nlevel=DEBUG\nformatter=arg0Formatter\nargs=('/var/log/cloud-init.log', 'a', 'UTF-8')\n"]], 'output': {'all': '| tee -a /var/log/cloud-init-output.log'}, 'network': {'config': 'disabled'}, 'datasource_list': ['Ec2', 'None'], 'datasource': {'Ec2': {'metadata_urls': ['http://169.254.169.254:80', 'http://[fd00:ec2::254]:80'], 'apply_full_imds_network_config': False}}, 'ssh_genkeytypes': ['ed25519', 'ecdsa'], 'users': ['default'], 'disable_root': True, 'mount_default_fields': [None, None, 'auto', 'defaults,nofail', '0', '2'], 'resize_rootfs': 'noblock', 'resize_rootfs_tmp': '/dev', 'ssh_pwauth': False, 'preserve_hostname': False, 'cloud_init_modules': ['migrator', 'seed_random', 'bootcmd', 'write-files', 'write-metadata', 'growpart', 'resizefs', 'disk_setup', 'mounts', 'set_hostname', 'update_hostname', 'update_etc_hosts', 'ca-certs', 'rsyslog', 'selinux', 'users-groups', 'ssh'], 'cloud_config_modules': ['ssh-import-id', 'keyboard', 'locale', 'set-passwords', 'yum-variables', 'yum-add-repo', 'ntp', 'timezone', 'disable-ec2-metadata', 'runcmd'], 'def_log_file': '/var/log/cloud-init.log', 'syslog_fix_perms': ['syslog:adm', 'root:adm', 'root:wheel', 'root:root'], 'vendor_data': {'enabled': True, 'prefix': []}, 'vendor_data2': {'enabled': True, 'prefix': []}}
2025-10-07 02:09:27,248 - cc_yum_variables.py[INFO]: No yum vars to delete
2025-10-07 02:09:27,249 - cc_yum_variables.py[INFO]: No yum vars to set
2025-10-07 02:09:27,249 - handlers.py[DEBUG]: finish: modules-config/config-yum-variables: SUCCESS: config-yum-variables ran successfully
2025-10-07 02:09:27,249 - modules.py[DEBUG]: Running module yum-add-repo (<module 'cloudinit.config.cc_yum_add_repo' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_yum_add_repo.py'>) with frequency once-per-instance
2025-10-07 02:09:27,249 - handlers.py[DEBUG]: start: modules-config/config-yum-add-repo: running config-yum-add-repo with frequency once-per-instance
2025-10-07 02:09:27,249 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-03facd8bcdc8558f2/sem/config_yum_add_repo - wb: [644] 24 bytes
2025-10-07 02:09:27,249 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-03facd8bcdc8558f2/sem/config_yum_add_repo (recursive=False)
2025-10-07 02:09:27,250 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-03facd8bcdc8558f2/sem/config_yum_add_repo (recursive=False)
2025-10-07 02:09:27,250 - helpers.py[DEBUG]: Running config-yum-add-repo using lock (<FileLock using file '/var/lib/cloud/instances/i-03facd8bcdc8558f2/sem/config_yum_add_repo'>)
2025-10-07 02:09:27,251 - cc_yum_add_repo.py[DEBUG]: Skipping module named yum-add-repo, no 'yum_repos' configuration found
2025-10-07 02:09:27,251 - handlers.py[DEBUG]: finish: modules-config/config-yum-add-repo: SUCCESS: config-yum-add-repo ran successfully
2025-10-07 02:09:27,251 - modules.py[DEBUG]: Running module ntp (<module 'cloudinit.config.cc_ntp' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_ntp.py'>) with frequency once-per-instance
2025-10-07 02:09:27,251 - handlers.py[DEBUG]: start: modules-config/config-ntp: running config-ntp with frequency once-per-instance
2025-10-07 02:09:27,251 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-03facd8bcdc8558f2/sem/config_ntp - wb: [644] 25 bytes
2025-10-07 02:09:27,251 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-03facd8bcdc8558f2/sem/config_ntp (recursive=False)
2025-10-07 02:09:27,252 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-03facd8bcdc8558f2/sem/config_ntp (recursive=False)
2025-10-07 02:09:27,252 - helpers.py[DEBUG]: Running config-ntp using lock (<FileLock using file '/var/lib/cloud/instances/i-03facd8bcdc8558f2/sem/config_ntp'>)
2025-10-07 02:09:27,252 - cc_ntp.py[DEBUG]: Skipping module named ntp, not present or disabled by cfg
2025-10-07 02:09:27,253 - handlers.py[DEBUG]: finish: modules-config/config-ntp: SUCCESS: config-ntp ran successfully
2025-10-07 02:09:27,253 - modules.py[DEBUG]: Running module timezone (<module 'cloudinit.config.cc_timezone' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_timezone.py'>) with frequency once-per-instance
2025-10-07 02:09:27,253 - handlers.py[DEBUG]: start: modules-config/config-timezone: running config-timezone with frequency once-per-instance
2025-10-07 02:09:27,253 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-03facd8bcdc8558f2/sem/config_timezone - wb: [644] 25 bytes
2025-10-07 02:09:27,253 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-03facd8bcdc8558f2/sem/config_timezone (recursive=False)
2025-10-07 02:09:27,254 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-03facd8bcdc8558f2/sem/config_timezone (recursive=False)
2025-10-07 02:09:27,254 - helpers.py[DEBUG]: Running config-timezone using lock (<FileLock using file '/var/lib/cloud/instances/i-03facd8bcdc8558f2/sem/config_timezone'>)
2025-10-07 02:09:27,254 - cc_timezone.py[DEBUG]: Skipping module named timezone, no 'timezone' specified
2025-10-07 02:09:27,255 - handlers.py[DEBUG]: finish: modules-config/config-timezone: SUCCESS: config-timezone ran successfully
2025-10-07 02:09:27,255 - modules.py[DEBUG]: Running module disable-ec2-metadata (<module 'cloudinit.config.cc_disable_ec2_metadata' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_disable_ec2_metadata.py'>) with frequency always
2025-10-07 02:09:27,255 - handlers.py[DEBUG]: start: modules-config/config-disable-ec2-metadata: running config-disable-ec2-metadata with frequency always
2025-10-07 02:09:27,255 - helpers.py[DEBUG]: Running config-disable-ec2-metadata using lock (<cloudinit.helpers.DummyLock object at 0x7f0fa174bf70>)
2025-10-07 02:09:27,255 - cc_disable_ec2_metadata.py[DEBUG]: Skipping module named disable-ec2-metadata, disabling the ec2 route not enabled
2025-10-07 02:09:27,255 - handlers.py[DEBUG]: finish: modules-config/config-disable-ec2-metadata: SUCCESS: config-disable-ec2-metadata ran successfully
2025-10-07 02:09:27,255 - modules.py[DEBUG]: Running module runcmd (<module 'cloudinit.config.cc_runcmd' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_runcmd.py'>) with frequency once-per-instance
2025-10-07 02:09:27,255 - handlers.py[DEBUG]: start: modules-config/config-runcmd: running config-runcmd with frequency once-per-instance
2025-10-07 02:09:27,255 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-03facd8bcdc8558f2/sem/config_runcmd - wb: [644] 25 bytes
2025-10-07 02:09:27,256 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-03facd8bcdc8558f2/sem/config_runcmd (recursive=False)
2025-10-07 02:09:27,256 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-03facd8bcdc8558f2/sem/config_runcmd (recursive=False)
2025-10-07 02:09:27,257 - helpers.py[DEBUG]: Running config-runcmd using lock (<FileLock using file '/var/lib/cloud/instances/i-03facd8bcdc8558f2/sem/config_runcmd'>)
2025-10-07 02:09:27,257 - cc_runcmd.py[DEBUG]: Skipping module named runcmd, no 'runcmd' key in configuration
2025-10-07 02:09:27,257 - handlers.py[DEBUG]: finish: modules-config/config-runcmd: SUCCESS: config-runcmd ran successfully
2025-10-07 02:09:27,257 - main.py[DEBUG]: Ran 9 modules with 0 failures
2025-10-07 02:09:27,257 - atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/status.json (via temporary file /var/lib/cloud/data/tmp9_jyz2jm) - w: [644] 512 bytes/chars
2025-10-07 02:09:27,258 - util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
2025-10-07 02:09:27,258 - util.py[DEBUG]: Read 10 bytes from /proc/uptime
2025-10-07 02:09:27,258 - util.py[DEBUG]: cloud-init mode 'modules' took 0.174 seconds (0.17)
2025-10-07 02:09:27,258 - handlers.py[DEBUG]: finish: modules-config: SUCCESS: running modules for config
2025-10-07 02:09:27,665 - util.py[DEBUG]: Cloud-init v. 22.2.2 running 'modules:final' at Tue, 07 Oct 2025 02:09:27 +0000. Up 9.25 seconds.
2025-10-07 02:09:27,669 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-10-07 02:09:27,669 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-10-07 02:09:27,671 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.amazon.Distro'>
2025-10-07 02:09:27,671 - modules.py[DEBUG]: Running module scripts-user (<module 'cloudinit.config.cc_scripts_user' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_scripts_user.py'>) with frequency always
2025-10-07 02:09:27,672 - handlers.py[DEBUG]: start: modules-final/config-scripts-user: running config-scripts-user with frequency always
2025-10-07 02:09:27,672 - helpers.py[DEBUG]: Running config-scripts-user using lock (<cloudinit.helpers.DummyLock object at 0x7f35d0551640>)
2025-10-07 02:09:27,672 - subp.py[DEBUG]: Running command ['/var/lib/cloud/instance/scripts/user-data.txt'] with allowed return codes [0] (shell=False, capture=False)
2025-10-07 02:09:33,557 - handlers.py[DEBUG]: finish: modules-final/config-scripts-user: SUCCESS: config-scripts-user ran successfully
2025-10-07 02:09:33,557 - main.py[DEBUG]: Ran 1 modules with 0 failures
2025-10-07 02:09:33,558 - atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/status.json (via temporary file /var/lib/cloud/data/tmp9qz0m81h) - w: [644] 540 bytes/chars
2025-10-07 02:09:33,558 - atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/result.json (via temporary file /var/lib/cloud/data/tmp7o170v58) - w: [644] 64 bytes/chars
2025-10-07 02:09:33,558 - util.py[DEBUG]: Creating symbolic link from '/run/cloud-init/result.json' => '../../var/lib/cloud/data/result.json'
2025-10-07 02:09:33,558 - util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
2025-10-07 02:09:33,558 - util.py[DEBUG]: Read 12 bytes from /proc/uptime
2025-10-07 02:09:33,558 - util.py[DEBUG]: cloud-init mode 'modules' took 5.961 seconds (4.67)
2025-10-07 02:09:33,558 - handlers.py[DEBUG]: finish: modules-final: SUCCESS: running modules for final
